export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_FAILURE = "GET_BLOGS_FAILURE";

export const UPDATE_BLOGS_REQUEST = "UPDATE_BLOGS_REQUEST";
export const UPDATE_BLOGS_SUCCESS = "UPDATE_BLOGS_SUCCESS";
export const UPDATE_BLOGS_FAILURE = "UPDATE_BLOGS_FAILURE";

export const DELETE_BLOGS_REQUEST = "DELETE_BLOGS_REQUEST";
export const DELETE_BLOGS_SUCCESS = "DELETE_BLOGS_SUCCESS";
export const DELETE_BLOGS_FAILURE = "DELETE_BLOGS_FAILURE";